services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: food_delivery_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - food_delivery_network

  user_service:
    build: ./userService
    container_name: user_service
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      DATABASE_URL: postgresql+asyncpg://test_user:test_password@postgres:5432/food_delivery_db
      SECRET_KEY: your-secret-key
      ADMIN_SECRET_KEY: your-admin-secret-key
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    networks:
      - food_delivery_network
    volumes:
      - ./userService:/app

  menu_service:
    build: ./menuService
    container_name: menu_service
    command: uvicorn app.main:app --host 0.0.0.0 --port 9000
    environment:
      DATABASE_URL: postgresql+asyncpg://test_user:test_password@postgres:5432/food_delivery_db
      USER_SERVICE_URL: http://user_service:8000
    depends_on:
      - postgres
      - user_service
    ports:
      - "9000:9000"
    networks:
      - food_delivery_network
    volumes:
      - ./menuService:/app

  payment_service:
    build: ./paymentService
    container_name: payment_service
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001
    environment:
      DATABASE_URL: postgresql+asyncpg://test_user:test_password@postgres:5432/food_delivery_db
      USER_SERVICE_URL: http://user_service:8000
    depends_on:
      - postgres
      - user_service
    ports:
      - "8001:8001"
    networks:
      - food_delivery_network
    volumes:
      - ./paymentService:/app

  notification_service:
    build: ./notificationService
    container_name: notification_service
    command: uvicorn app.main:app --host 0.0.0.0 --port 8002
    environment:
      DATABASE_URL: postgresql+asyncpg://test_user:test_password@postgres:5432/food_delivery_db
      USER_SERVICE_URL: http://user_service:8000
    depends_on:
      - postgres
      - user_service
    ports:
      - "8002:8002"
    networks:
      - food_delivery_network
    volumes:
      - ./notificationService:/app

  gateway_service:
    build:
      context: ./gatewayService
    container_name: gateway_service
    command: uvicorn main:app --host 0.0.0.0 --port 80
    ports:
      - "80:80"
    depends_on:
      - user_service
      - menu_service
      - payment_service
      - notification_service

networks:
  food_delivery_network:

volumes:
  postgres_data: