apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  type: {{ .Values.gatewayservice.service.type }}
  ports:
    - port: 80
      targetPort: 80

  selector:
    app: gateway-service

---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8002
      targetPort: 8002
  selector:
    app: notification-service

---
apiVersion: v1
kind: Service
metadata:
  name: menu-service
spec:
  type: {{.Values.service.type}}
  ports:
    - port: 9000
      targetPort: 9000
  selector:
    app: menu-service

---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  type: {{.Values.service.type}}
  ports:
    - port: 8001
      targetPort: 8001
  selector:
    app: payment-service

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: {{.Values.service.type}}
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: user-service


