name: CI/CD with Docker Compose
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build to Server via SSH
      - uses: appleboy/ssh-action@v1.0.0
      - with:
      - host: ${{ secrets.SERVER_HOST }}
      - username: ${{ secrets.SERVER_USER }}
      - key: ${{ secrets.SSH_PRIVATE_KEY }}
      - script: |
          cd /root/Artur/niaspoProject
          git pull
          docker-compose down
          docker-compose build

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Tests
      - uses: appleboy/ssh-action@v1.0.0
      - with:
      - host: ${{ secrets.SERVER_HOST }}
      - username: ${{ secrets.SERVER_USER }}
      - key: ${{ secrets.SSH_PRIVATE_KEY }}
      - script: |
          cd /root/Artur/niaspoProject
          curl localhost/docs


  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/Artur/niaspoProject
            git pull
            docker-compose down
            docker-compose up --build -d
